SELECT 
    b.AUTHOR_ID, 
    a.AUTHOR_NAME,
    b.CATEGORY,  
    SUM(s.SALES * b.PRICE) as TOTAL_SALES
FROM BOOK b 
JOIN AUTHOR a ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES s ON s.BOOK_ID = b.BOOK_ID
WHERE SALES_DATE like '2022-01%'
GROUP BY b.AUTHOR_ID, b.CATEGORY, a.AUTHOR_NAME
ORDER BY b.AUTHOR_ID, b.CATEGORY DESC;