WITH GEN1 AS (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL),
     GEN2 AS (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IN (SELECT ID FROM GEN1)),
     GEN3 AS (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IN (SELECT ID FROM GEN2))
SELECT ID FROM GEN3 ORDER BY ID;