SELECT 
    b.USER_ID, 
    b.NICKNAME, 
    CONCAT(b.CITY, ' ', b.STREET_ADDRESS1, ' ', b.STREET_ADDRESS2) as 전체주소,
    CONCAT(SUBSTR(b.TLNO, 1, 3), '-', SUBSTR(b.TLNO, 4, 4),  '-', SUBSTR(b.TLNO, 8, 4)) as 전화번호
FROM USED_GOODS_USER b
JOIN (
    SELECT WRITER_ID 
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3 
     ) a 
ON a.WRITER_ID = b.USER_ID
ORDER BY b.USER_ID DESC;