SELECT 
    ri.REST_ID,
    ri.REST_NAME,
    ri.FOOD_TYPE,
    ri.FAVORITES,
    ri.ADDRESS,
    rr.SCORE
FROM REST_INFO ri
JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) as SCORE
        FROM REST_REVIEW 
        GROUP BY REST_ID) rr
ON ri.REST_ID = rr.REST_ID
WHERE ri.ADDRESS like '서울%'
ORDER BY SCORE DESC, ri.FAVORITES DESC;