SELECT NAME, DATETIME
FROM (
    SELECT i.NAME, i.DATETIME 
    FROM ANIMAL_INS i 
    FULL OUTER JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
    WHERE o.DATETIME IS NULL
    ORDER BY i.DATETIME
)
WHERE ROWNUM <= 3;