SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fp.price * fo.amount) as TOTAL_SALES
FROM FOOD_PRODUCT fp 
JOIN FOOD_ORDER fo 
ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE produce_date >= DATE '2022-05-01' AND produce_date <  DATE '2022-06-01'
GROUP BY fp.PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES desc, fp.PRODUCT_ID asc;