SELECT 
    ch.HISTORY_ID,
    TRUNCATE(cc.DAILY_FEE * (DATEDIFF(ch.END_DATE, ch.START_DATE) + 1) *
    (1 - IFNULL(dp.DISCOUNT_RATE,0)/100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR cc
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ch
    ON cc.CAR_ID = ch.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
    ON cc.CAR_TYPE = dp.CAR_TYPE
    AND dp.DURATION_TYPE = 
        CASE
            WHEN DATEDIFF(ch.END_DATE, ch.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(ch.END_DATE, ch.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(ch.END_DATE, ch.START_DATE) + 1 >= 7 THEN '7일 이상'
        END
WHERE cc.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;