SELECT 
    MEMBER_NAME, 
    REVIEW_TEXT, 
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW rr
JOIN MEMBER_PROFILE mp ON rr.MEMBER_ID = mp.MEMBER_ID
WHERE rr.MEMBER_ID = (
    SELECT 
        MEMBER_ID
    FROM REST_REVIEW GROUP BY MEMBER_ID
    ORDER BY count(*) DESC LIMIT 1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;