# 희귀도가 RARE인 ID가 부모 ITEM에 있다면 그때 ITEM_ID를 기반으로 전부 출력




SELECT 
    ii.ITEM_ID, ii.ITEM_NAME, ii.RARITY
FROM ITEM_TREE it
JOIN ITEM_INFO ii ON it.ITEM_ID = ii.ITEM_ID
WHERE PARENT_ITEM_ID IN (
    SELECT 
        ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
ORDER BY ii.ITEM_ID DESC;