SELECT e1.ID, e1.GENOTYPE, e2.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA e1
JOIN ECOLI_DATA e2 ON e1.PARENT_ID = e2.ID
WHERE e1.PARENT_ID IS NOT NULL 
AND (e1.GENOTYPE & e2.GENOTYPE) = e2.GENOTYPE
ORDER BY e1.ID;