SELECT ID, FISH_NAME, MAX_LENGTH as LENGTH FROM FISH_INFO a JOIN FISH_NAME_INFO b ON a.FISH_TYPE = b.FISH_TYPE
JOIN
(SELECT fni.FISH_TYPE, MAX(LENGTH) as MAX_LENGTH
FROM FISH_INFO fi
JOIN FISH_NAME_INFO fni ON fi.FISH_TYPE = fni.FISH_TYPE
GROUP BY fni.FISH_TYPE) c ON a.FISH_TYPE = c.FISH_TYPE
WHERE a.LENGTH = c.MAX_LENGTH;