SELECT CONCAT('/home/grep/src/', b.BOARD_ID, '/', b.FILE_ID, b.FILE_NAME, b.FILE_EXT) as FILE_PATH
FROM USED_GOODS_BOARD a 
JOIN USED_GOODS_FILE b ON a.BOARD_ID = b.BOARD_ID
WHERE VIEWS = (SELECT max(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY b.FILE_ID DESC;